name: Build docker on release
on: 

  release:
    types: [published]

  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  RELEASE_TAG: ${{ github.event.release.tag_name }}

jobs:
  Build-Docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - 
        name: export Lowercase the Image name
        run: export IMAGE_NAME_LOWER="${${{ env.IMAGE_NAME }},,}"
      -
        name: Echo lowercase image name
        run: echo $IMAGE_NAME_LOWER
      - 
        name: Check out the repo
        uses: actions/checkout@v4

      - 
        name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/asullivan219/newsletter:latest, ${{ env.REGISTRY }}/asullivan219/newsletter:${{ env.RELEASE_TAG }}


